<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LoadBoardApp.Common\LoadBoardApp.Common.csproj" />
    <ProjectReference Include="..\LoadBoardApp.PublishedContentModels\LoadBoardApp.PublishedContentModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ViewModels\" />
  </ItemGroup>

</Project>
